# Each new term in the Fibonacci sequence is generated by adding 
# the previous two terms. By starting with 1 and 2, the first 10 
# terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values 
# do not exceed four million, find the sum of the even-valued terms.


def buildFibbs(fibbs, max)
  while fibbs[fibbs.length-1] < max do
    fibbs.push(fibbs[fibbs.length-1] + fibbs[fibbs.length-2])
  end
  fibbs
end

fibbs = [0, 1]
max = 4000000
fibbs = buildFibbs(fibbs, max)

sum = 0
for fib in fibbs do
  if fib % 2 == 0
    sum += fib
  end
end

puts sum
